==============================================================================
Jpetstore                                                                     
==============================================================================
Jpetstore 01                                                          [ ERROR ] Calling method 'end_keyword' of listener '/tmp/rfswarmagent/scripts/RFSListener3.py' failed: KeyError: 'doc'
| FAIL |
ConnectionError: HTTPConnectionPool(host='192.168.13.82', port=8080): Max retries exceeded with url: /jpetstore/actions/Catalog.action (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71ada1820110>: Failed to establish a new connection: [Errno 113] No route to host'))
------------------------------------------------------------------------------
Jpetstore                                                             | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  /tmp/rfswarmagent/logs/20240626_130059_jpetstore-nomon-quick/jpetstore_1_5_1719370863_1_1719370878/Jpetstore_01_output.xml
Log:     /tmp/rfswarmagent/logs/20240626_130059_jpetstore-nomon-quick/jpetstore_1_5_1719370863_1_1719370878/log.html
